# gen3 job run covid19-s3-etl S3_BUCKET <S3_BUCKET>
apiVersion: batch/v1
kind: Job
metadata:
  name: covid19-s3-etl
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      containers:
      - name: covid19-s3-etl
        imagePullPolicy: Always
        GEN3_COVID19-S3-ETL_IMAGE
        env:
        - name: S3_BUCKET
          GEN3_S3_BUCKET|-value: ""-|
        - name: doSlack
          GEN3_DO_SLACK|-value: "true"-|
        - name: gen3Env
          valueFrom:
            configMapKeyRef:
              name: manifest-global
              key: hostname
        - name: slackWebHook
          valueFrom:
            configMapKeyRef:
              name: global
              key: slack_webhook
        resources:
          limits:
            cpu: 0.5
            memory: 512Mi
        command: ["/bin/bash" ]
        args:
          - "-c"
          - |
            message="SUCCESS: covid19-s3-etl success in $gen3Env"
            result=0
            if ! bash /covid19-etl/s3_etl.sh; then
              result=1
              message="FAIL: covid19-s3-etl failure in $gen3Env"
            fi
            echo "$message"
            # no curl - ugh  
            cat - > /tmp/slack.py <<EOM
            import requests
            payload={"text": "$message"}
            r = requests.post("${slackWebHook}", json=payload)
            EOM
            if [[ -n "$slackWebHook" && "$doSlack" == "true" ]]; then
              python3 /tmp/slack.py
            fi
            exit $result
      restartPolicy: Never
